version: '2'
services:
  nginxbackend:
    container_name: nginxbackend
    build:
      context: ./docker/latest/
    links:
      - mysql

  mysql:  
    image: mysql:5.6
    container_name: mysqlapps
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=neooauth
    volumes:
      - ./data/mysql56/log:/var/log/mysql/:rw
      - ./data/mysql56/:/var/lib/mysql:rw
      - ./data/share/:/home/:rw
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"    
    

