version: '3.7'
services:
  web:
    extra_hosts:
      - "local.patterns.com:127.0.0.1"
    volumes:
      - ./docker/logs:/var/log/nginx
      - ~/.ssh:/root/.ssh
      - ./apps:/apps/:rw
      - ./docker/nginx/vhost:/etc/nginx/conf.d/:ro
  php:
    volumes:
      - ./apps:/apps/:rw
      - ./docker/logs:/var/log/php-fpm/7.3:rw
      - ./docker/php/php.conf.d/:/etc/php-7.3.d/:ro
 