version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginxlastest
    ports:
      - "80:80"
    links:
      - php
  php:
    image: php:7.3-fpm
    container_name: php73
    build:
      context: ./docker/php/ 
    

